name: BuildAndRun

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore CodeCubeConsole.sln

    - name: Build Code Generator
      run: msbuild CodeCubeConsole.sln /p:Configuration=Release
  
    - name: Run Site Generator
      run: ./CodeCubeConsole.exe
      working-directory: ./CodeCubeConsole/bin/Release/

    - name: publish site artifacts
      uses: actions/upload-artifact@v2
      with:
        name: published
        path: ./CodeCubeConsole/bin/Release/out/*
