name: BuildAndRun

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore CodeCubeConsole/CodeCubeConsole.csproj

    - name: Publish
      run: dotnet publish CodeCubeConsole/CodeCubeConsole.csproj -c Release -o publish --no-restore

    - name: Run Site Generator
      run: dotnet ./publish/CodeCubeConsole.dll

    - name: 📂 Sync files
      if: github.ref == 'refs/heads/master'
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: pdx1-shared-a3-05.dreamhost.com
        username: ${{ secrets.CODECUBE_FTP_USER }}
        password: ${{ secrets.CODECUBE_FTP_PASS }}
        local-dir: ./publish/out/
        server-dir: ./static_codecube/
    
    - name: publish site artifacts
      uses: actions/upload-artifact@v4
      with:
        name: published
        path: ./publish/out/*
