name: BuildAndRun

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore CodeCubeConsole.sln

    - name: Build Code Generator
      run: msbuild CodeCubeConsole.sln /p:Configuration=Release
  
    - name: Run Site Generator
      run: ./CodeCubeConsole.exe
      working-directory: ./CodeCubeConsole/bin/Release/

    - name: 📂 Sync files
      if: github.ref == 'refs/heads/master'
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: crane.dreamhost.com
        username: ${{ secrets.CODECUBE_FTP_USER }}
        password: ${{ secrets.CODECUBE_FTP_PASS }}
        local-dir: ./CodeCubeConsole/bin/Release/out/
        server-dir: ./static_codecube/
    
    - name: publish site artifacts
      uses: actions/upload-artifact@v4
      with:
        name: published
        path: ./CodeCubeConsole/bin/Release/out/*
